claseAEME/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from holaMundo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # Ejemplo 1 - holaMundo
    url('holaMundo/', views.holaMundo),
    # Ejemplo 2 - holaMundo2
    url('holaMundo2/', views.holaMundo2),
    # Ejemplo 3 - calendario
    url('calendario/', views.calendario),
    # Ejemplo 4 - calculadora
    url('calculadora/(?P<a>\d+)/(?P<b>\d+)', views.calculadora),

    # Ejemplo 5 - para aplicación 'master'
    path('master/', include('master.urls')),

]

master/urls.py
# Archivo creado para el ejemplo 5
from django.conf.urls import url
from django.urls import path
from . import views
app_name = 'master'

urlpatterns = [
    # vista 1 - inicio. Muestra el listado de asignaturas, profesores y alumnos
    path('', views.index, name='index'),

    # vista 2 - perfil de alumno
    url('alum/(?P<id>\d+)/', views.ver_alum),

    # vista 3 - página de asignatura
    url('asignatura/(?P<id>\d+)/', views.ver_asignatura),

    #vista 4 - formulario de búsqueda
    url('buscar_alum/', views.buscar_alum)

]

holaMundo/models.py
from django.db import models

# Create your models here.

master/models.py
from django.db import models

class Profesor(models.Model):
    nombre = models.CharField(max_length=30)
    apellidos = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return '%s %s' % (self.nombre, self.apellidos)

class Alumno (models.Model):
    nombre = models.CharField(max_length=30)
    apellidos = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return '%s %s' % (self.nombre, self.apellidos)

class Asignatura(models.Model):
    nombre = models.CharField(max_length=100)
    creditos = models.IntegerField()
    profesores = models.ManyToManyField(Profesor)
    curso = models.IntegerField()

    def __str__(self):
        return '%s' % (self.nombre)

class Matricula(models.Model):
    alumno = models.ForeignKey(Alumno, on_delete=models.CASCADE)
    asignatura = models.ForeignKey(Asignatura, on_delete=models.CASCADE)
    nota = models.FloatField()
    presentado = models.BooleanField(default=False)
    fecha = models.DateField()

    def __str__(self):
        return '%s %s - %s' % (self.alumno.nombre, self.alumno.apellidos, self.asignatura.nombre)

master/forms.py
from django import forms
from .models import *

class BuscarAlumForm(forms.Form):
   q = forms.CharField()

holaMundo/views.py
from django.shortcuts import render
from django.http import HttpResponse
from datetime import date
# Create your views here.

# Ejemplo 1 holaMundo - HttpResponse
def holaMundo(request):
    return HttpResponse("Hola mundo")

# Ejemplo 2 holaMundo2 - render(request, "plantilla.html")
def holaMundo2(request):
    return render(request,"holaMundo2.html")

# Ejemplo 3 calendario - con paso de variable date.today()
def calendario(request):
    fecha = date.today()
    return render(request,"calendario.html",{'fecha':fecha})

# Ejemplo 4 calculadora - urls con parámetros
def calculadora(request,a,b):
   numA = int(a)
   numB = int(b)
   suma = numA + numB
   resta = numA - numB
   return render(request, 'calculadora.html',{'numA':numA, 'numB':numB, 'suma': suma, 'resta':resta})

master/views.py
from django.shortcuts import render
from master.models import *
from django.shortcuts import get_object_or_404
from master.forms import *

# vista 1 - inicio. Muestra el listado de asignaturas, profesores y alumnos
def index(request):
    asignaturas = Asignatura.objects.all()
    profesores = Profesor.objects.all()
    alumnos = Alumno.objects.all()

    # para ordenar el listado por apellidos
    #alumnos = Alumno.objects.all().order_by('apellidos')

    return render(request,'indexMaster.html',{'asignaturas':asignaturas,'profesores':profesores,'alumnos':alumnos})

# vista 2 - alumno. Muestra sus datos personales y las asignaturas en las que se ha matriculado (con su nota si se ha presentado)
def ver_alum(request,id):
    # Acceso básico a datos
    #alum = Alumno.objects.get(id=id)

    # Acceso con control de excepciones
    alum = get_object_or_404(Alumno,id=id)

    # Filtrado de martrículas por alumno
    matriculas = Matricula.objects.filter(alumno=alum)

    return render(request,'alum.html',{'alum':alum, 'matriculas':matriculas})

# vista 3 - asignatura. Muestra los datos de las asignaturas y el alumnado matriculado con su calificación (si se ha presentado)
def ver_asignatura(request,id):
    asignatura = get_object_or_404(Asignatura,id=id)

    #Acceso a matriculas de esa asignatura
    matriculas = Matricula.objects.filter(asignatura=asignatura)

    return render(request,'asignatura.html',{'asignatura':asignatura, 'matriculas':matriculas})


# vista 4 - formulario para buscar
def buscar_alum(request):
   if request.method == 'GET':
      return render(request, 'buscar_alum.html')
   elif request.method == 'POST':
       form = BuscarAlumForm(request.POST)
       if form.is_valid():
           texto = form.cleaned_data["q"]
           alumnos = Alumno.objects.filter(apellidos__icontains=texto)
           return render(request,'listado_alumnado.html', {'alumnos':alumnos})
       else:
           return HttpResponseRedirect('/master/buscar_alum/')

holaMundo/templates/calculadora.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Calculadora</title>
</head>
<body>
    <h1>Calculadora</h1>
    <p>La <b>suma</b> de {{ numA }} y {{ numB }} es {{ suma }}</p>
    <p>La <b>resta</b>  de {{ numA }} y {{ numB }} es {{ resta }}</p>
    <p>¡Prueba a cambiar los números de la url!</p>
</body>
</html>

holaMundo/templates/calendario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Calendario</title>
</head>
<body>
<p>Hoy es {{ fecha }} (sin formato) </p>
<p>Hoy es {{ fecha|date:" j \d\e F \d\e Y"}} (con formato) </p>
<p>Hoy es {% now "jS F Y H:i" %} (usando sólo la plantilla)</p>


</body>
</html>

holaMundo/templates/holaMundo2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hola Mundo</title>
</head>
<body>

<h1>Hola mundo (versión 2)</h1>
</body>
</html>

master/templates/alum.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Alumn</title>
</head>
<body>
    <p>Nombre: {{ alum.nombre }} {{ alum.apellidos }}</p>
    <p>Email: {{ alum.email }}</p>
    <p>Asignaturas:</p>
    <ul>
    {%  for matricula in matriculas %}
     <li>{{ matricula.asignatura.nombre }} ({{ matricula.asignatura.creditos }} créditos)
        -
         {%  if matricula.presentado %}
             presentado ({{ matricula.nota }})
         {%  else %}
             no presentado
         {% endif %}

     </li>

    {%  endfor %}
    </ul>
</body>
</html>

master/templates/asignatura.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <p>Nombre:{{ asignatura.nombre }}</p>
    <p>Profesores:</p>
        {% for prof in asignatura.profesores.all %}
            {{ prof.nombre }} {{ prof.apellidos }}
        {% endfor %}
    <p>Alumnado:</p>
    <ul>
        {% for matricula in matriculas %}
            <li>{{ matricula.alumno.nombre }} -
                {%  if matricula.presentado %}
                    presentado ({{ matricula.nota }})
                {%  else %}
                    no presentado
                {% endif %}
                -
                {{ matricula.fecha }}
                </li>
        {%  endfor %}
    </ul>
</body>
</html>

master/templates/buscar_alum.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Buscar alumno/a</h1>

    <form action="/master/buscar_alum/" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <p>
          Apellidos:
          <input id="id_q" type="text" name="q" required>
      </p>

      <input type="submit" value="Buscar" />
</body>
</html>

master/templates/indexMaster.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Master</title>
</head>
<body>
 <h1>Página de inicio de la aplicación 'Máster'</h1>
    {% include "menu.html" %}
 <li> Alumnado matriculado
    <ul>
    {% for alum in alumnos %}
        <li><a href="./alum/{{ alum.id }}">{{ alum.nombre }} {{ alum.apellidos }}</a></li>
    {%  endfor %}
    </ul>
 </li>

 <li> Asignaturas disponibles
    <ul>
    {% for asignatura in asignaturas %}
        <li><a href="./asignatura/{{ asignatura.id }}">{{ asignatura.nombre }}</a></li>
    {%  endfor %}
    </ul>
 </li>

 <li> Profesorado
    <ul>
    {% for prof in profesores %}
        <li>{{ prof.nombre }} {{ prof.apellidos }}</li>
    {%  endfor %}
    </ul>
 </li>

</body>
</html>

master/templates/listado_alumnado.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
        <ul>
            {%  for alum in alumnos %}
                <li><a href="/master/alum/{{ alum.id }}">{{ alum.nombre }} {{ alum.apellidos }}</a></li>
            {% empty %}
                <p>No hay alumnos con esos apellidos.</p>
            {%  endfor %}
        </ul>
</body>
</html>

master/templates/menu.html
<p>
    <a href="/master">Inicio</a> | <a href="/master/buscar_alum">Buscar alumnado</a>
</p>